### ISSUE TITLE
How to install on Windows?

### ISSUE THREAD

**Issue by Endogen** [Lamden/contracting#290]
I have the issue that i can't install `contracting` on windows. I get this error:
```
pip install contracting
Defaulting to user installation because normal site-packages is not writeable
Collecting contracting
  Using cached contracting-1.0.5.tar.gz (81 kB)
Requirement already satisfied: astor in c:\users\strohmayer\appdata\roaming\python\python39\site-packages (from contracting) (0.8.1)
Requirement already satisfied: pymongo in c:\users\strohmayer\appdata\roaming\python\python39\site-packages (from contracting) (3.11.3)
Requirement already satisfied: autopep8 in c:\users\strohmayer\appdata\roaming\python\python39\site-packages (from contracting) (1.5.4)
Requirement already satisfied: stdlib_list in c:\users\strohmayer\appdata\roaming\python\python39\site-packages (from contracting) (0.8.0)
Requirement already satisfied: pycodestyle>=2.6.0 in c:\users\strohmayer\appdata\roaming\python\python39\site-packages (from autopep8->contracting) (2.6.0)
Requirement already satisfied: toml in c:\users\strohmayer\appdata\roaming\python\python39\site-packages (from autopep8->contracting) (0.10.2)
Using legacy 'setup.py install' for contracting, since package 'wheel' is not installed.
Installing collected packages: contracting
    Running setup.py install for contracting ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\strohmayer\\AppData\\Local\\Temp\\pip-install-806mi1nf\\contracting_4bdc3844d4004049aee96379c839b368\\setup.py'"'"'; __file__='"'"'C:\\Users\\strohmayer\\AppData\\Local\\Temp\\pip-install-806mi1nf\\contracting_4bdc3844d4004049aee96379c839b368\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\strohmayer\AppData\Local\Temp\pip-record-ibi_pazv\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\strohmayer\AppData\Roaming\Python\Python39\Include\contracting'
         cwd: C:\Users\strohmayer\AppData\Local\Temp\pip-install-806mi1nf\contracting_4bdc3844d4004049aee96379c839b368\
    Complete output (252 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\contracting
    copying contracting\client.py -> build\lib.win-amd64-3.9\contracting
    copying contracting\config.py -> build\lib.win-amd64-3.9\contracting
    copying contracting\__init__.py -> build\lib.win-amd64-3.9\contracting
    creating build\lib.win-amd64-3.9\tests
    copying tests\run.py -> build\lib.win-amd64-3.9\tests
    copying tests\utils.py -> build\lib.win-amd64-3.9\tests
    copying tests\__init__.py -> build\lib.win-amd64-3.9\tests
    creating build\lib.win-amd64-3.9\contracting\compilation
    copying contracting\compilation\compiler.py -> build\lib.win-amd64-3.9\contracting\compilation
    copying contracting\compilation\linter.py -> build\lib.win-amd64-3.9\contracting\compilation
    copying contracting\compilation\parser.py -> build\lib.win-amd64-3.9\contracting\compilation
    copying contracting\compilation\whitelists.py -> build\lib.win-amd64-3.9\contracting\compilation
    copying contracting\compilation\__init__.py -> build\lib.win-amd64-3.9\contracting\compilation
    creating build\lib.win-amd64-3.9\contracting\contracts
    copying contracting\contracts\submission.s.py -> build\lib.win-amd64-3.9\contracting\contracts
    copying contracting\contracts\__init__.py -> build\lib.win-amd64-3.9\contracting\contracts
    creating build\lib.win-amd64-3.9\contracting\db
    copying contracting\db\contract.py -> build\lib.win-amd64-3.9\contracting\db
    copying contracting\db\driver.py -> build\lib.win-amd64-3.9\contracting\db
    copying contracting\db\encoder.py -> build\lib.win-amd64-3.9\contracting\db
    copying contracting\db\orm.py -> build\lib.win-amd64-3.9\contracting\db
    copying contracting\db\__init__.py -> build\lib.win-amd64-3.9\contracting\db
    creating build\lib.win-amd64-3.9\contracting\execution
    copying contracting\execution\executor.py -> build\lib.win-amd64-3.9\contracting\execution
    copying contracting\execution\module.py -> build\lib.win-amd64-3.9\contracting\execution
    copying contracting\execution\runtime.py -> build\lib.win-amd64-3.9\contracting\execution
    copying contracting\execution\__init__.py -> build\lib.win-amd64-3.9\contracting\execution
    creating build\lib.win-amd64-3.9\contracting\stdlib
    copying contracting\stdlib\env.py -> build\lib.win-amd64-3.9\contracting\stdlib
    copying contracting\stdlib\__init__.py -> build\lib.win-amd64-3.9\contracting\stdlib
    creating build\lib.win-amd64-3.9\contracting\execution\metering
    copying contracting\execution\metering\__init__.py -> build\lib.win-amd64-3.9\contracting\execution\metering
    creating build\lib.win-amd64-3.9\contracting\stdlib\bridge
    copying contracting\stdlib\bridge\access.py -> build\lib.win-amd64-3.9\contracting\stdlib\bridge
    copying contracting\stdlib\bridge\decimal.py -> build\lib.win-amd64-3.9\contracting\stdlib\bridge
    copying contracting\stdlib\bridge\hashing.py -> build\lib.win-amd64-3.9\contracting\stdlib\bridge
    copying contracting\stdlib\bridge\imports.py -> build\lib.win-amd64-3.9\contracting\stdlib\bridge
    copying contracting\stdlib\bridge\orm.py -> build\lib.win-amd64-3.9\contracting\stdlib\bridge
    copying contracting\stdlib\bridge\random.py -> build\lib.win-amd64-3.9\contracting\stdlib\bridge
    copying contracting\stdlib\bridge\time.py -> build\lib.win-amd64-3.9\contracting\stdlib\bridge
    copying contracting\stdlib\bridge\__init__.py -> build\lib.win-amd64-3.9\contracting\stdlib\bridge
    creating build\lib.win-amd64-3.9\tests\final_gov
    copying tests\final_gov\test_add_members.py -> build\lib.win-amd64-3.9\tests\final_gov
    copying tests\final_gov\test_foundation.py -> build\lib.win-amd64-3.9\tests\final_gov
    copying tests\final_gov\test_members.py -> build\lib.win-amd64-3.9\tests\final_gov
    copying tests\final_gov\test_rewards.py -> build\lib.win-amd64-3.9\tests\final_gov
    copying tests\final_gov\test_stamps.py -> build\lib.win-amd64-3.9\tests\final_gov
    copying tests\final_gov\__init__.py -> build\lib.win-amd64-3.9\tests\final_gov
    creating build\lib.win-amd64-3.9\tests\governance
    copying tests\governance\test_election_house.py -> build\lib.win-amd64-3.9\tests\governance
    copying tests\governance\test_even_simpler_election_house.py -> build\lib.win-amd64-3.9\tests\governance
    copying tests\governance\test_foundation.py -> build\lib.win-amd64-3.9\tests\governance
    copying tests\governance\test_masternodes.py -> build\lib.win-amd64-3.9\tests\governance
    copying tests\governance\test_master_candidates.py -> build\lib.win-amd64-3.9\tests\governance
    copying tests\governance\test_more_flexible_election_house.py -> build\lib.win-amd64-3.9\tests\governance
    copying tests\governance\test_new_candidates.py -> build\lib.win-amd64-3.9\tests\governance
    copying tests\governance\test_new_masternodes.py -> build\lib.win-amd64-3.9\tests\governance
    copying tests\governance\test_pending_masters.py -> build\lib.win-amd64-3.9\tests\governance
    copying tests\governance\test_rewards.py -> build\lib.win-amd64-3.9\tests\governance
    copying tests\governance\test_simple_voting_contract.py -> build\lib.win-amd64-3.9\tests\governance
    copying tests\governance\test_stamps.py -> build\lib.win-amd64-3.9\tests\governance
    copying tests\governance\__init__.py -> build\lib.win-amd64-3.9\tests\governance
    creating build\lib.win-amd64-3.9\tests\integration
    copying tests\integration\test_atomic_swap.py -> build\lib.win-amd64-3.9\tests\integration
    copying tests\integration\test_builtins_locked_off.py -> build\lib.win-amd64-3.9\tests\integration
    copying tests\integration\test_complex_contracts.py -> build\lib.win-amd64-3.9\tests\integration
    copying tests\integration\test_complex_object_setting.py -> build\lib.win-amd64-3.9\tests\integration
    copying tests\integration\test_constructor_args.py -> build\lib.win-amd64-3.9\tests\integration
    copying tests\integration\test_datetime_contracts.py -> build\lib.win-amd64-3.9\tests\integration
    copying tests\integration\test_dynamic_imports.py -> build\lib.win-amd64-3.9\tests\integration
    copying tests\integration\test_executor_submission_process.py -> build\lib.win-amd64-3.9\tests\integration
    copying tests\integration\test_misc_contracts.py -> build\lib.win-amd64-3.9\tests\integration
    copying tests\integration\test_pixel_game.py -> build\lib.win-amd64-3.9\tests\integration
    copying tests\integration\test_rich_ctx_calling.py -> build\lib.win-amd64-3.9\tests\integration
    copying tests\integration\test_run_private_function.py -> build\lib.win-amd64-3.9\tests\integration
    copying tests\integration\test_senecaCompiler_integration.py -> build\lib.win-amd64-3.9\tests\integration
    copying tests\integration\test_seneca_client_randoms.py -> build\lib.win-amd64-3.9\tests\integration
    copying tests\integration\test_seneca_client_replaces_executor.py -> build\lib.win-amd64-3.9\tests\integration
    copying tests\integration\test_stamp_deduction.py -> build\lib.win-amd64-3.9\tests\integration
    copying tests\integration\__init__.py -> build\lib.win-amd64-3.9\tests\integration
    creating build\lib.win-amd64-3.9\tests\performance
    copying tests\performance\prof_transfer.py -> build\lib.win-amd64-3.9\tests\performance
    copying tests\performance\test_transfer.py -> build\lib.win-amd64-3.9\tests\performance
    copying tests\performance\__init__.py -> build\lib.win-amd64-3.9\tests\performance
    creating build\lib.win-amd64-3.9\tests\security
    copying tests\security\test_erc20_token_hacks.py -> build\lib.win-amd64-3.9\tests\security
    copying tests\security\__init__.py -> build\lib.win-amd64-3.9\tests\security
    creating build\lib.win-amd64-3.9\tests\unit
    copying tests\unit\test_client.py -> build\lib.win-amd64-3.9\tests\unit
    copying tests\unit\test_context_data_struct.py -> build\lib.win-amd64-3.9\tests\unit
    copying tests\unit\test_datetime.py -> build\lib.win-amd64-3.9\tests\unit
    copying tests\unit\test_decimal.py -> build\lib.win-amd64-3.9\tests\unit
    copying tests\unit\test_driver.py -> build\lib.win-amd64-3.9\tests\unit
    copying tests\unit\test_encode.py -> build\lib.win-amd64-3.9\tests\unit
    copying tests\unit\test_imports_stdlib.py -> build\lib.win-amd64-3.9\tests\unit
    copying tests\unit\test_linter.py -> build\lib.win-amd64-3.9\tests\unit
    copying tests\unit\test_module.py -> build\lib.win-amd64-3.9\tests\unit
    copying tests\unit\test_new_cache_driver.py -> build\lib.win-amd64-3.9\tests\unit
    copying tests\unit\test_new_contract_driver.py -> build\lib.win-amd64-3.9\tests\unit
    copying tests\unit\test_new_driver.py -> build\lib.win-amd64-3.9\tests\unit
    copying tests\unit\test_orm.py -> build\lib.win-amd64-3.9\tests\unit
    copying tests\unit\test_parser.py -> build\lib.win-amd64-3.9\tests\unit
    copying tests\unit\test_runtime.py -> build\lib.win-amd64-3.9\tests\unit
    copying tests\unit\test_stdlib_hashing.py -> build\lib.win-amd64-3.9\tests\unit
    copying tests\unit\test_timedelta.py -> build\lib.win-amd64-3.9\tests\unit
    copying tests\unit\__init__.py -> build\lib.win-amd64-3.9\tests\unit
    creating build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\atomic_swaps.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\bad_time.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\bastardcoin.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\builtin_lib.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\child_test.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\constructor_args_contract.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\contracting.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\currency.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\dater.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\dynamic_import.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\dynamic_importing.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\erc20_clone.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\float_issue.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\foreign_thing.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\importing_that.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\import_test.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\import_this.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\inf_loop.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\i_use_env.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\json_tests.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\leaky.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\mathtime.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\owner_stuff.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\parent_test.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\pass_hash.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\private_methods.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\stubucks.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\tejastokens.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\test_client.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\test_construct_function_works.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\test_hashing_works.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\test_orm_foreign_hash_contract.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\test_orm_foreign_key_contract.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\test_orm_hash_contract.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\test_orm_no_contract_access.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\test_orm_variable_contract.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\test_pass_hash.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\test_time.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\thing.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\time_storage.s.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    copying tests\integration\test_contracts\__init__.py -> build\lib.win-amd64-3.9\tests\integration\test_contracts
    creating build\lib.win-amd64-3.9\tests\unit\precompiled
    copying tests\unit\precompiled\compiled_token.py -> build\lib.win-amd64-3.9\tests\unit\precompiled
    copying tests\unit\precompiled\updated_submission.py -> build\lib.win-amd64-3.9\tests\unit\precompiled
    copying tests\unit\precompiled\__init__.py -> build\lib.win-amd64-3.9\tests\unit\precompiled
    creating build\lib.win-amd64-3.9\tests\unit\test_sys_contracts
    copying tests\unit\test_sys_contracts\bad_lint.s.py -> build\lib.win-amd64-3.9\tests\unit\test_sys_contracts
    copying tests\unit\test_sys_contracts\compile_this.s.py -> build\lib.win-amd64-3.9\tests\unit\test_sys_contracts
    copying tests\unit\test_sys_contracts\currency.s.py -> build\lib.win-amd64-3.9\tests\unit\test_sys_contracts
    copying tests\unit\test_sys_contracts\good_lint.s.py -> build\lib.win-amd64-3.9\tests\unit\test_sys_contracts
    copying tests\unit\test_sys_contracts\module1.py -> build\lib.win-amd64-3.9\tests\unit\test_sys_contracts
    copying tests\unit\test_sys_contracts\module2.py -> build\lib.win-amd64-3.9\tests\unit\test_sys_contracts
    copying tests\unit\test_sys_contracts\module3.py -> build\lib.win-amd64-3.9\tests\unit\test_sys_contracts
    copying tests\unit\test_sys_contracts\module4.py -> build\lib.win-amd64-3.9\tests\unit\test_sys_contracts
    copying tests\unit\test_sys_contracts\module5.py -> build\lib.win-amd64-3.9\tests\unit\test_sys_contracts
    copying tests\unit\test_sys_contracts\module6.py -> build\lib.win-amd64-3.9\tests\unit\test_sys_contracts
    copying tests\unit\test_sys_contracts\module7.py -> build\lib.win-amd64-3.9\tests\unit\test_sys_contracts
    copying tests\unit\test_sys_contracts\module8.py -> build\lib.win-amd64-3.9\tests\unit\test_sys_contracts
    copying tests\unit\test_sys_contracts\module_func.py -> build\lib.win-amd64-3.9\tests\unit\test_sys_contracts
    copying tests\unit\test_sys_contracts\__init__.py -> build\lib.win-amd64-3.9\tests\unit\test_sys_contracts
    running egg_info
    writing contracting.egg-info\PKG-INFO
    writing dependency_links to contracting.egg-info\dependency_links.txt
    writing requirements to contracting.egg-info\requires.txt
    writing top-level names to contracting.egg-info\top_level.txt
    reading manifest file 'contracting.egg-info\SOURCES.txt'
    writing manifest file 'contracting.egg-info\SOURCES.txt'
    copying contracting\execution\metering\tracer.c -> build\lib.win-amd64-3.9\contracting\execution\metering
    running build_ext
    building 'contracting.execution.metering.tracer' extension
    creating build\temp.win-amd64-3.9
    creating build\temp.win-amd64-3.9\Release
    creating build\temp.win-amd64-3.9\Release\contracting
    creating build\temp.win-amd64-3.9\Release\contracting\execution
    creating build\temp.win-amd64-3.9\Release\contracting\execution\metering
    C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.23.28105\bin\HostX86\x64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\program files\python39\include -Ic:\program files\python39\include -IC:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.23.28105\include -IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\shared -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\winrt -IC:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\cppwinrt /Tccontracting/execution/metering/tracer.c /Fobuild\temp.win-amd64-3.9\Release\contracting/execution/metering/tracer.obj
    tracer.c
    contracting/execution/metering/tracer.c(9): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "sys/resource.h": No such file or directory
    Traceback (most recent call last):
      File "c:\program files\python39\lib\distutils\_msvccompiler.py", line 401, in compile
        self.spawn(args)
      File "c:\program files\python39\lib\distutils\_msvccompiler.py", line 507, in spawn
        return super().spawn(cmd)
      File "c:\program files\python39\lib\distutils\ccompiler.py", line 910, in spawn
        spawn(cmd, dry_run=self.dry_run)
      File "c:\program files\python39\lib\distutils\spawn.py", line 87, in spawn
        raise DistutilsExecError(
    distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.23.28105\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\strohmayer\AppData\Local\Temp\pip-install-806mi1nf\contracting_4bdc3844d4004049aee96379c839b368\setup.py", line 36, in build_extension
        build_ext.build_extension(self, ext)
      File "c:\program files\python39\lib\distutils\command\build_ext.py", line 529, in build_extension
        objects = self.compiler.compile(sources,
      File "c:\program files\python39\lib\distutils\_msvccompiler.py", line 403, in compile
        raise CompileError(msg)
    distutils.errors.CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.23.28105\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\strohmayer\AppData\Local\Temp\pip-install-806mi1nf\contracting_4bdc3844d4004049aee96379c839b368\setup.py", line 45, in <module>
        setup(
      File "c:\program files\python39\lib\site-packages\setuptools\__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "c:\program files\python39\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\program files\python39\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\program files\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\program files\python39\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\program files\python39\lib\distutils\command\install.py", line 546, in run
        self.run_command('build')
      File "c:\program files\python39\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\program files\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\program files\python39\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\program files\python39\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\program files\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\strohmayer\AppData\Local\Temp\pip-install-806mi1nf\contracting_4bdc3844d4004049aee96379c839b368\setup.py", line 27, in run
        build_ext.run(self)
      File "c:\program files\python39\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "c:\program files\python39\lib\distutils\command\build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "c:\program files\python39\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "C:\Users\strohmayer\AppData\Local\Temp\pip-install-806mi1nf\contracting_4bdc3844d4004049aee96379c839b368\setup.py", line 38, in build_extension
        raise BuildFailed()
    __main__.BuildFailed
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\strohmayer\\AppData\\Local\\Temp\\pip-install-806mi1nf\\contracting_4bdc3844d4004049aee96379c839b368\\setup.py'"'"'; __file__='"'"'C:\\Users\\strohmayer\\AppData\\Local\\Temp\\pip-install-806mi1nf\\contracting_4bdc3844d4004049aee96379c839b368\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\strohmayer\AppData\Local\Temp\pip-record-ibi_pazv\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\strohmayer\AppData\Roaming\Python\Python39\Include\contracting' Check the logs for full command output.
```

I'm using Python 3.9.1 on Windows 10. This issue didn't help me since i don't know how to get `python3-dev` working on Windows: https://github.com/Lamden/contracting/issues/288

EDIT: I just saw the instructions here: https://contracting.lamden.io/windows/
Will check that first and then see if that helps me

**Comment by Endogen** [comment]
Can't install since my Windows 10 version doesn't meet requirements (corporate laptop runs on an older Windows version)
